# Generated by Django 5.1.4 on 2025-01-02 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threePagesBackend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='audio/')),
                ('transcript', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
