# Generated by Django 5.1.4 on 2025-01-02 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threePagesBackend', '0002_audiodata_delete_mymodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiodata',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='audiodata',
            name='transcript',
        ),
    ]
